In [9]:
import numpy as np

In [13]:
myarr = np.array([[1, 2, 3, 4, 5]])
myarr

array([[1, 2, 3, 4, 5]])

In [14]:
myarr[0, 1]

np.int64(2)

In [16]:
listarray = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
listarray.shape

(3, 3)

In [20]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range = np.arange(10)
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
lspace = np.linspace(1, 5, 10)
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [23]:
empty = np.empty((3, 3))
empty

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
empty_like = np.empty_like(listarray)
empty_like

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
three_like = np.ones_like(listarray)
three_like

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [28]:
ide = np.identity(10)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
arr = np.arange(25)
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr.sum(axis=0)  
arr.sum(axis=1)# column wise sum

array([ 6, 15, 24])

In [42]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [43]:
arr.flat
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [44]:
arr.ndim

2

In [49]:
one = np.array([1, 3, 2])

In [50]:
one.argmax()

np.int64(1)

In [51]:
one.argmin()

np.int64(0)

In [52]:
one.argsort()

array([0, 2, 1])